import { qualificationValuesBySubField, type QualificationSubField } from './inference/qualifications.js';
import type { BucketName } from './types.js';

export interface FacetedFiniteBucket<SubField extends string = string> {
  valuesBySubField: Readonly<Record<SubField, readonly string[]>>;
}

export const FACETED_FINITE_VALUES = {
  qualifications: {
    valuesBySubField: qualificationValuesBySubField(),
  } satisfies FacetedFiniteBucket<QualificationSubField>,
} as const satisfies Partial<Record<BucketName, FacetedFiniteBucket>>;

export const FINITE_VALUES = {
  workplace: ['remote', 'hybrid', 'onsite', 'abroad', 'field_based', 'flexible'],
  employment: ['full_time', 'part_time', 'contract', 'temporary', 'seasonal', 'per_diem', 'internship'],
  schedule: [
    '9_to_5',
    'flexible_hours',
    'fixed_shift',
    'async',
    'day_shift',
    'swing_shift',
    'night_shift',
    'rotational_shift',
    'weekend_only',
    'split_shift',
    '4x10_schedule',
    'on_call',
    '24_7_standby',
  ],
  level: ['entry_level', 'junior', 'mid_level', 'senior', 'lead', 'manager', 'director', 'executive'],
  company_size: ['startup', 'small', 'mid_growing', 'mid_stable', 'large', 'enterprise', 'global'],
  sector: [
    'agriculture_agri_business',
    'automotive',
    'aviation',
    'banking_financial_services',
    'construction',
    'education',
    'energy',
    'food_beverage',
    'government',
    'hospital_healthcare',
    'hospitality',
    'industrial_services',
    'information_technology',
    'insurance',
    'manufacturing',
    'media_advertising',
    'nonprofit',
    'pharma_biotech',
    'professional_services',
    'real_estate_property',
    'retailer',
    'security',
    'telecom',
    'transportation',
    'utility_provider',
    'warehouse_logistics',
  ],
  job_function: [
    'administration',
    'animal_care_childcare_cleaning',
    'architecture_design',
    'arts_entertainment',
    'banking',
    'business_development',
    'community_social_services',
    'consulting_strategy',
    'customer_support',
    'education_training',
    'engineering',
    'finance_accounting',
    'health_safety',
    'healthcare',
    'hospitality_food_service',
    'human_resources',
    'insurance',
    'it_software_data',
    'legal_compliance',
    'management',
    'marketing_communications',
    'mechanical_technical',
    'mining_natural_resources',
    'operations_logistics',
    'physical_manual_work',
    'procurement',
    'project_management',
    'quality_assurance',
    'research_development',
    'sales_commerce',
    'security',
    'skilled_trades',
    'transport_driving',
    'volunteering_internships',
  ],
  benefits: [
    'meal_vouchers',
    'health_insurance',
    // 'private_medical',
    'tool_allowance',
    'life_insurance',
    'transport_allowance',
    'paid_training',
    'transport_provided',
    // fuel_card,
    'paid_time_off',
    //'paid_sick_leave',
    //'extra_vacation_days',
    'company_car',
    'pension_scheme',
    'accommodation_provided',
    'phone_provided',
    'parental_leave',
    'uniform_provided',
    'laptop_provided',
    'employee_discount',
    'disability_insurance',
    'relocation_support',
    'uniform_cleaning',
    'wellness_allowance',
    'cafeteria',
    'flexible_stipends',
    'hsa_fsa',
  ],
  compensation: [
    'equity',
    'stock_options',
    'rsus',
    'phantom_shares',
    'annual_bonus',
    'sign_on_bonus',
    'performance_bonus',
    'retention_bonus',
    'profit_sharing',
    'commission',
    'ote',
    'cash_tips',
    'pooled_tips',
    'shift_differential',
    'overtime_1_5x',
    'overtime_2x',
    'piece_rate',
    'daily_payout',
    'per_diem_pay',
    'on_call_standby_pay',
    'dispatch_bonus',
    'hazard_pay',
    'holiday_pay',
    'sunday_premium',
    'attendance_bonus',
    'call_out_pay',
    'christmas_bonus',
    'fourteenth_salary',
    'night_premium',
    'weekend_premium',
    'vacation_bonus',
  ],
  collar_kind: ['white_collar', 'blue_collar', 'grey_collar'],
} as const satisfies Partial<Record<BucketName, readonly string[]>>;

export const SECTOR_LABELS = {
  agriculture_agri_business: 'Agriculture & Agribusiness',
  automotive: 'Automotive',
  aviation: 'Aviation',
  banking_financial_services: 'Banking & Financial Services',
  construction: 'Construction',
  education: 'Education',
  energy: 'Energy',
  food_beverage: 'Food & Beverage',
  government: 'Public Sector',
  hospital_healthcare: 'Healthcare',
  hospitality: 'Hospitality',
  industrial_services: 'Industrial Services',
  information_technology: 'Information Technology',
  insurance: 'Insurance',
  manufacturing: 'Manufacturing',
  media_advertising: 'Media & Advertising',
  nonprofit: 'Nonprofit',
  pharma_biotech: 'Pharmaceuticals & Biotechnology',
  professional_services: 'Professional Services',
  real_estate_property: 'Real Estate & Property',
  retailer: 'Retail & Consumer Goods',
  security: 'Security',
  telecom: 'Telecommunications',
  transportation: 'Transportation',
  utility_provider: 'Utilities',
  warehouse_logistics: 'Warehousing & Logistics',
} as const satisfies Record<(typeof FINITE_VALUES.sector)[number], string>;

export type FiniteBucket = keyof typeof FINITE_VALUES;
export type FiniteValues = typeof FINITE_VALUES;

/**
 * ESCO occupation family taxonomy nodes (esco_1_2_1), copied from
 * packages/occupation/artifacts/runtime/occupation-family-token-relevance.esco_1_2_1.json
 * (familiesByLocale.en). `id` is the source `familyNodeId`; `slug` is its
 * normalized form. Not yet wired into FINITE_VALUES/BucketName.
 */
export const OCCUPATION_FAMILIES = [
  { id: 14659, slug: 'commissioned_armed_forces_officers', label: 'Commissioned armed forces officers' },
  { id: 14662, slug: 'non_commissioned_armed_forces_officers', label: 'Non-commissioned armed forces officers' },
  { id: 14665, slug: 'armed_forces_occupations_other_ranks', label: 'Armed forces occupations, other ranks' },
  { id: 14669, slug: 'legislators_and_senior_officials', label: 'Legislators and senior officials' },
  { id: 14674, slug: 'managing_directors_and_chief_executives', label: 'Managing directors and chief executives' },
  {
    id: 14677,
    slug: 'business_services_and_administration_managers',
    label: 'Business services and administration managers',
  },
  { id: 14682, slug: 'sales_marketing_and_development_managers', label: 'Sales, marketing and development managers' },
  {
    id: 14687,
    slug: 'production_managers_in_agriculture_forestry_and_fisheries',
    label: 'Production managers in agriculture, forestry and fisheries',
  },
  {
    id: 14690,
    slug: 'manufacturing_mining_construction_and_distribution_managers',
    label: 'Manufacturing, mining, construction, and distribution managers',
  },
  {
    id: 14695,
    slug: 'information_and_communications_technology_service_managers',
    label: 'Information and communications technology service managers',
  },
  { id: 14697, slug: 'professional_services_managers', label: 'Professional services managers' },
  { id: 14706, slug: 'hotel_and_restaurant_managers', label: 'Hotel and restaurant managers' },
  { id: 14709, slug: 'retail_and_wholesale_trade_managers', label: 'Retail and wholesale trade managers' },
  { id: 14711, slug: 'other_services_managers', label: 'Other services managers' },
  { id: 14716, slug: 'physical_and_earth_science_professionals', label: 'Physical and earth science professionals' },
  {
    id: 14721,
    slug: 'mathematicians_actuaries_and_statisticians',
    label: 'Mathematicians, actuaries and statisticians',
  },
  { id: 14723, slug: 'life_science_professionals', label: 'Life science professionals' },
  {
    id: 14727,
    slug: 'engineering_professionals_excluding_electrotechnology',
    label: 'Engineering professionals (excluding electrotechnology)',
  },
  { id: 14735, slug: 'electrotechnology_engineers', label: 'Electrotechnology engineers' },
  {
    id: 14739,
    slug: 'architects_planners_surveyors_and_designers',
    label: 'Architects, planners, surveyors and designers',
  },
  { id: 14747, slug: 'medical_doctors', label: 'Medical doctors' },
  { id: 14750, slug: 'nursing_and_midwifery_professionals', label: 'Nursing and midwifery professionals' },
  {
    id: 14753,
    slug: 'traditional_and_complementary_medicine_professionals',
    label: 'Traditional and complementary medicine professionals',
  },
  { id: 14757, slug: 'veterinarians', label: 'Veterinarians' },
  { id: 14759, slug: 'other_health_professionals', label: 'Other health professionals' },
  { id: 14769, slug: 'university_and_higher_education_teachers', label: 'University and higher education teachers' },
  { id: 14771, slug: 'vocational_education_teachers', label: 'Vocational education teachers' },
  { id: 14773, slug: 'secondary_education_teachers', label: 'Secondary education teachers' },
  {
    id: 14775,
    slug: 'primary_school_and_early_childhood_teachers',
    label: 'Primary school and early childhood teachers',
  },
  { id: 14778, slug: 'other_teaching_professionals', label: 'Other teaching professionals' },
  { id: 14787, slug: 'finance_professionals', label: 'Finance professionals' },
  { id: 14791, slug: 'administration_professionals', label: 'Administration professionals' },
  {
    id: 14796,
    slug: 'sales_marketing_and_public_relations_professionals',
    label: 'Sales, marketing and public relations professionals',
  },
  {
    id: 14802,
    slug: 'software_and_applications_developers_and_analysts',
    label: 'Software and applications developers and analysts',
  },
  { id: 14808, slug: 'database_and_network_professionals', label: 'Database and network professionals' },
  { id: 14814, slug: 'legal_professionals', label: 'Legal professionals' },
  { id: 14818, slug: 'librarians_archivists_and_curators', label: 'Librarians, archivists and curators' },
  { id: 14821, slug: 'social_and_religious_professionals', label: 'Social and religious professionals' },
  { id: 14828, slug: 'authors_journalists_and_linguists', label: 'Authors, journalists and linguists' },
  { id: 14832, slug: 'creative_and_performing_artists', label: 'Creative and performing artists' },
  {
    id: 14842,
    slug: 'physical_and_engineering_science_technicians',
    label: 'Physical and engineering science technicians',
  },
  {
    id: 14852,
    slug: 'mining_manufacturing_and_construction_supervisors',
    label: 'Mining, manufacturing and construction supervisors',
  },
  { id: 14856, slug: 'process_control_technicians', label: 'Process control technicians' },
  {
    id: 14863,
    slug: 'life_science_technicians_and_related_associate_professionals',
    label: 'Life science technicians and related associate professionals',
  },
  {
    id: 14867,
    slug: 'ship_and_aircraft_controllers_and_technicians',
    label: 'Ship and aircraft controllers and technicians',
  },
  { id: 14874, slug: 'medical_and_pharmaceutical_technicians', label: 'Medical and pharmaceutical technicians' },
  {
    id: 14879,
    slug: 'nursing_and_midwifery_associate_professionals',
    label: 'Nursing and midwifery associate professionals',
  },
  {
    id: 14882,
    slug: 'traditional_and_complementary_medicine_associate_professionals',
    label: 'Traditional and complementary medicine associate professionals',
  },
  { id: 14884, slug: 'veterinary_technicians_and_assistants', label: 'Veterinary technicians and assistants' },
  { id: 14886, slug: 'other_health_associate_professionals', label: 'Other health associate professionals' },
  {
    id: 14897,
    slug: 'financial_and_mathematical_associate_professionals',
    label: 'Financial and mathematical associate professionals',
  },
  { id: 14903, slug: 'sales_and_purchasing_agents_and_brokers', label: 'Sales and purchasing agents and brokers' },
  { id: 14908, slug: 'business_services_agents', label: 'Business services agents' },
  {
    id: 14914,
    slug: 'administrative_and_specialised_secretaries',
    label: 'Administrative and specialised secretaries',
  },
  {
    id: 14919,
    slug: 'regulatory_government_associate_professionals',
    label: 'Regulatory government associate professionals',
  },
  {
    id: 14927,
    slug: 'legal_social_and_religious_associate_professionals',
    label: 'Legal, social and religious associate professionals',
  },
  { id: 14931, slug: 'sports_and_fitness_workers', label: 'Sports and fitness workers' },
  {
    id: 14935,
    slug: 'artistic_cultural_and_culinary_associate_professionals',
    label: 'Artistic, cultural and culinary associate professionals',
  },
  {
    id: 14942,
    slug: 'information_and_communications_technology_operations_and_user_support_technicians',
    label: 'Information and communications technology operations and user support technicians',
  },
  {
    id: 14947,
    slug: 'telecommunications_and_broadcasting_technicians',
    label: 'Telecommunications and broadcasting technicians',
  },
  { id: 14952, slug: 'general_office_clerks', label: 'General office clerks' },
  { id: 14954, slug: 'secretaries_general', label: 'Secretaries (general)' },
  { id: 14956, slug: 'keyboard_operators', label: 'Keyboard operators' },
  {
    id: 14960,
    slug: 'tellers_money_collectors_and_related_clerks',
    label: 'Tellers, money collectors and related clerks',
  },
  { id: 14965, slug: 'client_information_workers', label: 'Client information workers' },
  { id: 14975, slug: 'numerical_clerks', label: 'Numerical clerks' },
  { id: 14979, slug: 'material_recording_and_transport_clerks', label: 'Material-recording and transport clerks' },
  { id: 14984, slug: 'other_clerical_support_workers', label: 'Other clerical support workers' },
  { id: 14994, slug: 'travel_attendants_conductors_and_guides', label: 'Travel attendants, conductors and guides' },
  { id: 14998, slug: 'cooks', label: 'Cooks' },
  { id: 15000, slug: 'waiters_and_bartenders', label: 'Waiters and bartenders' },
  {
    id: 15003,
    slug: 'hairdressers_beauticians_and_related_workers',
    label: 'Hairdressers, beauticians and related workers',
  },
  { id: 15006, slug: 'building_and_housekeeping_supervisors', label: 'Building and housekeeping supervisors' },
  { id: 15010, slug: 'other_personal_services_workers', label: 'Other personal services workers' },
  { id: 15018, slug: 'street_and_market_salespersons', label: 'Street and market salespersons' },
  { id: 15021, slug: 'shop_salespersons', label: 'Shop salespersons' },
  { id: 15025, slug: 'cashiers_and_ticket_clerks', label: 'Cashiers and ticket clerks' },
  { id: 15027, slug: 'other_sales_workers', label: 'Other sales workers' },
  { id: 15036, slug: 'child_care_workers_and_teachers_aides', label: 'Child care workers and teachers’ aides' },
  { id: 15039, slug: 'personal_care_workers_in_health_services', label: 'Personal care workers in health services' },
  { id: 15044, slug: 'protective_services_workers', label: 'Protective services workers' },
  { id: 15052, slug: 'market_gardeners_and_crop_growers', label: 'Market gardeners and crop growers' },
  { id: 15057, slug: 'animal_producers', label: 'Animal producers' },
  { id: 15062, slug: 'mixed_crop_and_animal_producers', label: 'Mixed crop and animal producers' },
  { id: 15065, slug: 'forestry_and_related_workers', label: 'Forestry and related workers' },
  { id: 15067, slug: 'fishery_workers_hunters_and_trappers', label: 'Fishery workers, hunters and trappers' },
  { id: 15083, slug: 'building_frame_and_related_trades_workers', label: 'Building frame and related trades workers' },
  {
    id: 15090,
    slug: 'building_finishers_and_related_trades_workers',
    label: 'Building finishers and related trades workers',
  },
  {
    id: 15098,
    slug: 'painters_building_structure_cleaners_and_related_trades_workers',
    label: 'Painters, building structure cleaners and related trades workers',
  },
  {
    id: 15103,
    slug: 'sheet_and_structural_metal_workers_moulders_and_welders_and_related_workers',
    label: 'Sheet and structural metal workers, moulders and welders, and related workers',
  },
  {
    id: 15109,
    slug: 'blacksmiths_toolmakers_and_related_trades_workers',
    label: 'Blacksmiths, toolmakers and related trades workers',
  },
  { id: 15114, slug: 'machinery_mechanics_and_repairers', label: 'Machinery mechanics and repairers' },
  { id: 15120, slug: 'handicraft_workers', label: 'Handicraft workers' },
  { id: 15130, slug: 'printing_trades_workers', label: 'Printing trades workers' },
  {
    id: 15135,
    slug: 'electrical_equipment_installers_and_repairers',
    label: 'Electrical equipment installers and repairers',
  },
  {
    id: 15139,
    slug: 'electronics_and_telecommunications_installers_and_repairers',
    label: 'Electronics and telecommunications installers and repairers',
  },
  {
    id: 15143,
    slug: 'food_processing_and_related_trades_workers',
    label: 'Food processing and related trades workers',
  },
  {
    id: 15150,
    slug: 'wood_treaters_cabinet_makers_and_related_trades_workers',
    label: 'Wood treaters, cabinet-makers and related trades workers',
  },
  { id: 15154, slug: 'garment_and_related_trades_workers', label: 'Garment and related trades workers' },
  { id: 15161, slug: 'other_craft_and_related_workers', label: 'Other craft and related workers' },
  {
    id: 15169,
    slug: 'mining_and_mineral_processing_plant_operators',
    label: 'Mining and mineral processing plant operators',
  },
  {
    id: 15174,
    slug: 'metal_processing_and_finishing_plant_operators',
    label: 'Metal processing and finishing plant operators',
  },
  {
    id: 15177,
    slug: 'chemical_and_photographic_products_plant_and_machine_operators',
    label: 'Chemical and photographic products plant and machine operators',
  },
  {
    id: 15180,
    slug: 'rubber_plastic_and_paper_products_machine_operators',
    label: 'Rubber, plastic and paper products machine operators',
  },
  {
    id: 15184,
    slug: 'textile_fur_and_leather_products_machine_operators',
    label: 'Textile, fur and leather products machine operators',
  },
  {
    id: 15193,
    slug: 'food_and_related_products_machine_operators',
    label: 'Food and related products machine operators',
  },
  {
    id: 15195,
    slug: 'wood_processing_and_papermaking_plant_operators',
    label: 'Wood processing and papermaking plant operators',
  },
  {
    id: 15198,
    slug: 'other_stationary_plant_and_machine_operators',
    label: 'Other stationary plant and machine operators',
  },
  { id: 15204, slug: 'assemblers', label: 'Assemblers' },
  {
    id: 15209,
    slug: 'locomotive_engine_drivers_and_related_workers',
    label: 'Locomotive engine drivers and related workers',
  },
  { id: 15212, slug: 'car_van_and_motorcycle_drivers', label: 'Car, van and motorcycle drivers' },
  { id: 15215, slug: 'heavy_truck_and_bus_drivers', label: 'Heavy truck and bus drivers' },
  { id: 15218, slug: 'mobile_plant_operators', label: 'Mobile plant operators' },
  { id: 15223, slug: 'ships_deck_crews_and_related_workers', label: 'Ships’ deck crews and related workers' },
  {
    id: 15227,
    slug: 'domestic_hotel_and_office_cleaners_and_helpers',
    label: 'Domestic, hotel and office cleaners and helpers',
  },
  {
    id: 15230,
    slug: 'vehicle_window_laundry_and_other_hand_cleaning_workers',
    label: 'Vehicle, window, laundry and other hand cleaning workers',
  },
  {
    id: 15236,
    slug: 'agricultural_forestry_and_fishery_labourers',
    label: 'Agricultural, forestry and fishery labourers',
  },
  { id: 15244, slug: 'mining_and_construction_labourers', label: 'Mining and construction labourers' },
  { id: 15248, slug: 'manufacturing_labourers', label: 'Manufacturing labourers' },
  { id: 15251, slug: 'transport_and_storage_labourers', label: 'Transport and storage labourers' },
  { id: 15257, slug: 'food_preparation_assistants', label: 'Food preparation assistants' },
  { id: 15261, slug: 'street_and_related_service_workers', label: 'Street and related service workers' },
  { id: 15263, slug: 'street_vendors_excluding_food', label: 'Street vendors (excluding food)' },
  { id: 15266, slug: 'refuse_workers', label: 'Refuse workers' },
  { id: 15270, slug: 'other_elementary_workers', label: 'Other elementary workers' },
] as const;
