import type { BucketName } from './types.js';

export const FINITE_VALUES = {
  workplace: ['remote', 'hybrid', 'onsite', 'abroad', 'field_based', 'flexible'],
  employment: ['full_time', 'part_time', 'contract', 'temporary', 'seasonal', 'per_diem', 'internship'],
  schedule: [
    '9_to_5',
    'flexible_hours',
    'fixed_shift',
    'async',
    'day_shift',
    'swing_shift',
    'night_shift',
    'rotational_shift',
    'weekend_only',
    'split_shift',
    '4x10_schedule',
    'on_call',
    '24_7_standby',
  ],
  level: ['entry_level', 'junior', 'mid_level', 'senior', 'lead', 'manager', 'director', 'executive'],
  sector: [
    'agriculture_agri_business',
    'automotive',
    'aviation',
    'banking_financial_services',
    'construction',
    'education',
    'energy',
    'food_beverage',
    'government',
    'hospital_healthcare',
    'hospitality',
    'industrial_services',
    'information_technology',
    'insurance',
    'manufacturing',
    'media_advertising',
    'nonprofit',
    'pharma_biotech',
    'professional_services',
    'real_estate_property',
    'retailer',
    'security',
    'telecom',
    'transportation',
    'utility_provider',
    'warehouse_logistics',
  ],
  job_function: [
    'administration',
    'animal_care_childcare_cleaning',
    'architecture_design',
    'arts_entertainment',
    'banking',
    'business_development',
    'community_social_services',
    'consulting_strategy',
    'customer_support',
    'education_training',
    'engineering',
    'finance_accounting',
    'health_safety',
    'healthcare',
    'hospitality_food_service',
    'human_resources',
    'insurance',
    'it_software_data',
    'legal_compliance',
    'management',
    'marketing_communications',
    'mechanical_technical',
    'mining_natural_resources',
    'operations_logistics',
    'physical_manual_work',
    'procurement',
    'project_management',
    'quality_assurance',
    'research_development',
    'sales_commerce',
    'security',
    'skilled_trades',
    'transport_driving',
    'volunteering_internships',
  ],
  benefits: [
    'meal_vouchers',
    'private_medical',
    'tool_allowance',
    'health_insurance',
    'life_insurance',
    'transport_allowance',
    'paid_training',
    'transport_provided',
    'paid_time_off',
    'company_car',
    'pension_scheme',
    'accommodation_provided',
    'phone_provided',
    'parental_leave',
    'uniform_provided',
    'laptop_provided',
    'employee_discount',
    'disability_insurance',
    'paid_sick_leave',
    'fuel_card',
    'extra_vacation_days',
    'relocation_support',
    'uniform_cleaning',
    'wellness_allowance',
  ],
  compensation: [
    'equity',
    'stock_options',
    'rsus',
    'annual_bonus',
    'sign_on_bonus',
    'performance_bonus',
    'retention_bonus',
    'profit_sharing',
    'commission',
    'ote',
    'cash_tips',
    'pooled_tips',
    'shift_differential',
    'overtime_1_5x',
    'overtime_2x',
    'piece_rate',
    'daily_payout',
    'per_diem_pay',
    'on_call_standby_pay',
    'dispatch_bonus',
    'hazard_pay',
    'holiday_pay',
    'sunday_premium',
    'attendance_bonus',
    'call_out_pay',
    'christmas_bonus',
    'fourteenth_salary',
    'night_premium',
    'weekend_premium',
  ],
  collar_kind: ['white_collar', 'blue_collar', 'grey_collar'],
} as const satisfies Partial<Record<BucketName, readonly string[]>>;

export const SECTOR_LABELS = {
  agriculture_agri_business: 'Agriculture & Agribusiness',
  automotive: 'Automotive',
  aviation: 'Aviation',
  banking_financial_services: 'Banking & Financial Services',
  construction: 'Construction',
  education: 'Education',
  energy: 'Energy',
  food_beverage: 'Food & Beverage',
  government: 'Public Sector',
  hospital_healthcare: 'Healthcare',
  hospitality: 'Hospitality',
  industrial_services: 'Industrial Services',
  information_technology: 'Information Technology',
  insurance: 'Insurance',
  manufacturing: 'Manufacturing',
  media_advertising: 'Media & Advertising',
  nonprofit: 'Nonprofit',
  pharma_biotech: 'Pharmaceuticals & Biotechnology',
  professional_services: 'Professional Services',
  real_estate_property: 'Real Estate & Property',
  retailer: 'Retail & Consumer Goods',
  security: 'Security',
  telecom: 'Telecommunications',
  transportation: 'Transportation',
  utility_provider: 'Utilities',
  warehouse_logistics: 'Warehousing & Logistics',
} as const satisfies Record<(typeof FINITE_VALUES.sector)[number], string>;

export type FiniteBucket = keyof typeof FINITE_VALUES;
export type FiniteValues = typeof FINITE_VALUES;
