/**
 * Stopword / common-word gate for single-word lexical matches.
 *
 * The lexical index intentionally accepts short, distinctive surface forms
 * ("sql", "aws", "hr", "cnc") that embeddings handle poorly. But several ESCO
 * aliases are ordinary words ("design", "experiment", "software", "days", "it")
 * which, matched as a bare unigram, produce high-confidence false positives.
 *
 * We only apply this gate to *single-word* lexical hits; multi-word alias matches
 * ("meal vouchers", "work from home", "cluj napoca") remain unrestricted. The set
 * covers English function words plus the specific common content words observed to
 * appear as dictionary aliases, and the and/or conjunctions of ro/hu/et.
 */
const STOPWORDS = new Set<string>([
  // English function words
  'the',
  'and',
  'or',
  'a',
  'an',
  'to',
  'of',
  'in',
  'on',
  'at',
  'for',
  'with',
  'by',
  'as',
  'is',
  'are',
  'be',
  'we',
  'you',
  'our',
  'your',
  'it',
  'its',
  'this',
  'that',
  'from',
  'will',
  'can',
  'all',
  'any',
  'not',
  'no',
  'yes',
  'per',
  // common content words seen as ESCO/dictionary aliases (offenders)
  'design',
  'build',
  'develop',
  'development',
  'create',
  'creating',
  'make',
  'plan',
  'planning',
  'manage',
  'management',
  'work',
  'working',
  'experiment',
  'software',
  'hardware',
  'system',
  'systems',
  'service',
  'services',
  'support',
  'team',
  'teams',
  'project',
  'projects',
  'process',
  'processes',
  'product',
  'day',
  'days',
  'time',
  'full',
  'part',
  'new',
  'use',
  'using',
  'help',
  'lead',
  'role',
  'job',
  'skill',
  'skills',
  'experience',
  'company',
  'business',
  'client',
  'customer',
  'quality',
  'data',
  'report',
  'reporting',
  'staff',
  'people',
  // "contract" alone is the ubiquitous "contract de muncă" (employment contract),
  // not the employment:contract (contractor/freelance) sense — needs a qualifier.
  'contract',
  'colaborare',
  'b2b',
  // ambiguous level unigrams: "project/time/stock management" and "lead
  // generation"/"sales lead" must not tag level:manager / level:lead; and
  // "intermediate/intermediar" usually means language/skill level, not seniority.
  // The multi-word forms ("team lead", "mid-level") still match.
  'management',
  'lead',
  'intermediate',
  'intermediar',
  // Romanian function words
  'si',
  'sau',
  'de',
  'la',
  'cu',
  'un',
  'o',
  'pentru',
  'in',
  'pe',
  'ale',
  'ai',
  'este',
  'sunt',
  'care',
  'sa',
  'se',
  'ce',
  'nu',
  'da',
  'din',
  'ca',
  'fi',
  // Hungarian function words
  'es',
  'vagy',
  'az',
  'egy',
  'van',
  'nem',
  'is',
  'meg',
  'hogy',
  'de',
  'mint',
  'majd',
  'ez',
  'ezt',
  'ki',
  'be',
  'fel',
  'le',
  'el',
  'ha',
  'csak',
  // Estonian function words
  'ja',
  'voi',
  'ei',
  'on',
  'see',
  'kui',
  'ka',
  'nii',
  'et',
  'aga',
  'ning',
  'kas',
  'ta',
  'ma',
  'sa',
  'me',
  'te',
  'oma',
  'seda',
]);

/** True when a single-word lexical unigram is too common to trust on its own. */
export function isStopword(word: string): boolean {
  return STOPWORDS.has(word);
}
